services:
  postgres-ucpa:
    image: postgres:15.8-alpine
    container_name: ucpa-postgres
    restart: always
    networks:
      - back
    ports:
      - '${UCPA_DATABASE_PORT_API:-5466}:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ucpa_facilitator
    env_file:
      - .env

  chrome:
    image: ghcr.io/browserless/chromium
    container_name: chrome
    ports:
      - '3033:3000'
    restart: always
    networks:
      - back

  app-ucpa:
    build:
      context: .
    container_name: app-ucpa
    depends_on:
      - postgres-ucpa
      - chrome
    command: >
      sh -c "npm run db:migrate && npm start"
    restart: always
    networks:
      - back
      - web
    volumes:
      - ./certs:/app/certs
    environment:
      NODE_ENV: production
    env_file:
      - .env
    labels:
      traefik.enable: true
      traefik.docker.network: web
      traefik.http.routers.ucpa.rule: Host(`${URL}`)
      traefik.http.routers.ucpa.entrypoints: websecure
      traefik.http.routers.ucpa.tls: true
      traefik.http.routers.ucpa.tls.certresolver: letsencrypt

networks:
  back:
  web:
    external: true
